name: corpulentpangolin
description: A diplomacy client

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  cloud_firestore:
  flutter_web_plugins:
    sdk: flutter
  auto_route:
  google_sign_in:
  provider:
  firebase_core:
  firebase_auth:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  webview_flutter:
  http:
  brotli:
  js:
  cupertino_icons:
  url_launcher:
  intl:
  universal_html:

dependency_overrides:
  auto_route:
    git:
      url: https://github.com/biklas7/auto_route_library.git
      ref: chore/update-flutter-beta
      path: auto_route

dev_dependencies:
  import_sorter:
  auto_route_generator:
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

flutter_intl:
  enabled: true
