// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN9Wex1TxNbr-gtMpFiewHsCn6l_hrNHE',
    appId: '1:527588078303:web:910de1bc30bafe0a5d2f6a',
    messagingSenderId: '527588078303',
    projectId: 'corpulentpangolin',
    authDomain: 'corpulentpangolin.firebaseapp.com',
    storageBucket: 'corpulentpangolin.appspot.com',
    measurementId: 'G-53YL6VYFPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP7dx4m0yCZDRxoIBt8PYkLToS6B_97Go',
    appId: '1:527588078303:android:dc9176ccf9174b055d2f6a',
    messagingSenderId: '527588078303',
    projectId: 'corpulentpangolin',
    storageBucket: 'corpulentpangolin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAkF-GVfoIYg6FaLCRy6L3QcRnkhcNupg',
    appId: '1:527588078303:ios:a25d7a01ace6c6785d2f6a',
    messagingSenderId: '527588078303',
    projectId: 'corpulentpangolin',
    storageBucket: 'corpulentpangolin.appspot.com',
    androidClientId:
        '527588078303-1okjhub8r6346qei741tf4i53u8v3v49.apps.googleusercontent.com',
    iosClientId:
        '527588078303-e8i5bovlj6tb1balrm46pud81hill4e3.apps.googleusercontent.com',
    iosBundleId: 'com.diplicity.corpulentpangolin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAkF-GVfoIYg6FaLCRy6L3QcRnkhcNupg',
    appId: '1:527588078303:ios:a25d7a01ace6c6785d2f6a',
    messagingSenderId: '527588078303',
    projectId: 'corpulentpangolin',
    storageBucket: 'corpulentpangolin.appspot.com',
    androidClientId:
        '527588078303-1okjhub8r6346qei741tf4i53u8v3v49.apps.googleusercontent.com',
    iosClientId:
        '527588078303-e8i5bovlj6tb1balrm46pud81hill4e3.apps.googleusercontent.com',
    iosBundleId: 'com.diplicity.corpulentpangolin',
  );
}
