name: Deploy

on:
    push:
        branches: ["main", "beta"]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Install Flutter
              uses: subosito/flutter-action@v1
            - name: Extract branch name
              run: echo "BRANCH_NAME=$(echo ${GITHUB_REF##*/})" >> ${GITHUB_ENV}
            - name: Create .ssh directory
              run: mkdir ${HOME}/.ssh && chmod 700 ${HOME}/.ssh
            - name: Copy SSH key for iBrave
              run: ( echo "${{ secrets.IBRAVE_SSH_KEY }}" > ${HOME}/.ssh/id_rsa ) && chmod 600 ${HOME}/.ssh/id_rsa
            - name: Copy SSH host key for iBrave
              run: ( echo "${{ secrets.IBRAVE_SSH_HOST_KEY }}" >> ${HOME}/.ssh/known_hosts ) && chmod 600 ${HOME}/.ssh/known_hosts
            - name: Verify iBrave SSH access
              run: env LC_ALL=C ssh oort.se@ssh.ibrave.io date
            - name: Build release
              run: flutter build web
            - name: Sync release to iBrave
              run: env LC_ALL=C rsync -v -a --delete build/web/ oort.se@ssh.ibrave.io:public_html/${BRANCH_NAME}-pangolin.diplicity.com/
