name: Deploy iOS

on:
    push:
        branches: ["main", "beta"]

jobs:
    deploy:
        runs-on: macos-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Select Xcode version
              run: sudo xcode-select -s '/Applications/Xcode_11.3.app/Contents/Developer'
            - name: Bundle install
              run: cd ./ios && bundle install
            - name: Install Flutter
              uses: subosito/flutter-action@v1
            - name: Build release
              run: flutter build ios